document.getElementsByTagName("h1")[0].style.backgroundColor = "green"
document.getElementsByTagName("h1")[0].style.padding = "20px"
document.getElementsByTagName("h1")[0].style.width = "100%"
document.getElementsByTagName("h1")[0].style.marginLeft = "-20px"
document.getElementsByTagName("h1")[0].style.marginTop = "-20px"

document.querySelector("body").style.backgroundColor = "silver"
document.querySelector("section").style.backgroundColor = "LightSalmon"
document.getElementsByTagName("section")[1].style.backgroundColor = "Gold"
document.getElementsByTagName("h3")[0].style.backgroundColor = "purple"
document.getElementsByTagName("h3")[1].style.backgroundColor = "purple"
document.getElementsByTagName("h3")[2].style.backgroundColor = "black"
document.getElementsByTagName("h3")[3].style.backgroundColor = "black"
document.getElementById("footer-container").style.backgroundColor = "DarkGreen"